// <auto-generated/>
// This file auto generated by the Wintellect TFS Build Number Targets.
// See https://github.com/Wintellect/WintellectTFSBuildNumber for more information.
module SharedAssemblyFileVersion

open System.Reflection

[<assembly: AssemblyVersion("0.1.10717")>]
[<assembly: AssemblyFileVersion("0.1.10717")>]
[<assembly: AssemblyInformationalVersion("0.1.10717-debug+2004")>]

()
